### ISSUE TITLE
Version 1.1 is not working!

### ISSUE THREAD

**Issue by JesterEE** [JesterEE/SteamMonsterMinigameJoinScript#1]
In version 1.1, when joining a game, even when specifying a game ID, it loaded me into the previous game that was joined.  Obviously, not what I wanted.  This should be easily fixed, but it's not that easy to test since games aren't filling quickly later on in the day.

**Comment by dspecht** [comment]
http://i.imgur.com/Ys3w4E9.png vs http://i.imgur.com/VZTN4qQ.png    Notice the URL. one has a / at the end. now lets look at line 6 ''' // @match      http://steamcommunity.com/minigame/* ''' see how it is matching /*  if you remove that and reload with the url without the /    you get http://i.imgur.com/SFQsap8.png   (or a working copy) so that needs to be looked. possible solution is regex.

**Comment by JesterEE** [comment]
@dspecht, while valid, this isn't the issue I was talking about.  For whatever reason, the join command does not seem to be processed correctly since I:

1. Was not able to join the game I requested.
2. Was taken to a previously entered game.

I would expect that if the join was working, it would have left the current game and placed me either in the game I requested, or a new game.  I will try and get to the bottom of this now.

**Comment by dspecht** [comment]
ya looking at it now with someone else. Also the attempt to get enter working does it for any key http://i.imgur.com/y8uvoip.gif

**Comment by JesterEE** [comment]
Ya, I just fixed that now ... I did something stupid.

Right now I'm doing some testing ... I think it was working, just my keydown event was not correct.

**Comment by dspecht** [comment]
ya currently looking at things aswell we should be able to resolve this by the reset hopefully. (because it is really nice)

**Comment by JesterEE** [comment]
Well, I'm glad someone likes it :)
Here is the code I'm currently working on:
https://github.com/JesterEE/SteamMonsterMinigameJoinScript/blob/dev/join.js

The joining before wanting to is fixed (added a listener to for the Enter key) ... just getting bad requests from the server when I click go.  I think Steam doesn't like the DOS attack this is doing, so I slowing it down a bit.

Testing continues

**Comment by Soulflare3** [comment]
I'm actually tinkering with this as well, and was writing a69291b387b05c35ad799ca0e3b208a3d7b85b4c to fix the onkeydown problem, which you found as well, just formatted a little differently.

The error code seems to be on steam's end, but not entirely sure yet. One thing I notice is that while the script is loaded, if we hit "start a new game" it just loads into the in-progress game...

**Comment by JesterEE** [comment]
Ok, I fixed most, but not all of the errors.

The biggest issue was the fact that GM/TM use special functions to send HTTP requests.  So, I modified what was needed and it seems to work.  Next, if you are currently in a game, you must leave it first before entering another.  I cut this part out of the script yesterday thinking it wasn't important, but apparently it is.  So I added it back in with the appropriate request, but it's not working.  This is where I'm stuck.  I'm just not sure why this request isn't being read correctly by the Steam servers (Bad Request Error 400).  The newest development branch is in the dev branch.

https://github.com/JesterEE/SteamMonsterMinigameJoinScript/blob/dev/join.js

**Comment by JesterEE** [comment]
So, I have very little motivation to finish this.  The console methods of joining are efficient/sufficient and with only a handful of days left in the event, it probably won't get used anyway.

Thanks for everyone's interest, and if anyone wants to fork the dev branch to finish it, I encourage you to do so.  Pust here and let me know if you do so I can forward people to yours and I can check it out myself.  If nothing else, this solidified my hatred for javascript. ;)
